### ISSUE TITLE
Issue with AreaRegistration in Global.asax

### ISSUE THREAD

**Issue by KathleenDollard** [csharpfritz/WebFormsTest#25]
Are areas supported?

This line: 

```
        AreaRegistration.RegisterAllAreas();
```

in

```
   protected void Application_Start(object sender, EventArgs e
```

of 

```
global.asax.cs
```

results in the error below (slightly munged).

The test is

```
    [TestMethod]
    public void CanIgetMasterPage()
    {
        var sut = WebApplicationProxy.GetPageByLocation("~/MasterPages/Main.Master") as Main;

        Assert.IsNotNull(sut);


    }
```

and the base test class is

namespace xxx.yyy.WebFormsTestSpike
{

```
public class WebFormsTestBase
{

    protected readonly MockRepository _mockery;
    protected readonly Mock<HttpContextBase> contextMock;
    protected readonly Mock<HttpResponseBase> responseMock;
    protected readonly Mock<HttpRequestBase> requestMock;

    public WebFormsTestBase()
    {

        _mockery = new MockRepository(MockBehavior.Loose);

        contextMock = _mockery.Create<HttpContextBase>();

        responseMock = _mockery.Create<HttpResponseBase>();
        contextMock.SetupGet(c => c.Response).Returns(responseMock.Object);
        contextMock.SetupGet(c => c.IsDebuggingEnabled).Returns(true);

        requestMock = _mockery.Create<HttpRequestBase>();
        contextMock.SetupGet(c => c.Request).Returns(requestMock.Object);

        InitializeWebApplicationProxy();
    }

    private void InitializeWebApplicationProxy()
    {
        Uri codeBase = new Uri(GetType().Assembly.CodeBase);
        var currentFolder = new DirectoryInfo(Path.GetDirectoryName(codeBase.LocalPath));
        var webFolder = currentFolder.Parent.Parent.Parent.GetDirectories("xxx.yyy.Web")[0];

        WebApplicationProxy.Create(webFolder.FullName, true);
    }
}
```

}

System.InvalidOperationException was unhandled by user code
  HResult=-2146233079
  Message=This method cannot be called during the application's pre-start initialization phase.
  Source=System.Web
  StackTrace:
       at System.Web.Compilation.BuildManager.EnsureTopLevelFilesCompiled()
       at System.Web.Compilation.BuildManager.GetReferencedAssemblies()
       at System.Web.Mvc.BuildManagerWrapper.System.Web.Mvc.IBuildManager.GetReferencedAssemblies()
       at System.Web.Mvc.TypeCacheUtil.FilterTypesInAssemblies(IBuildManager buildManager, Predicate`1 predicate)
       at System.Web.Mvc.TypeCacheUtil.GetFilteredTypesFromAssemblies(String cacheName, Predicate`1 predicate, IBuildManager buildManager)
       at System.Web.Mvc.AreaRegistration.RegisterAllAreas(RouteCollection routes, IBuildManager buildManager, Object state)
       at System.Web.Mvc.AreaRegistration.RegisterAllAreas(Object state)
       at System.Web.Mvc.AreaRegistration.RegisterAllAreas()
       at xxx.yyy.Web.Global.Application_Start(Object sender, EventArgs e) in C:\zzz\Repos\MarketOnce2\Products\xxx\yyy\xxx.yyy.Web\Global.asax.cs:line 117
  InnerException:

**Comment by KathleenDollard** [comment]
Sorry, should have added, this happens at 

 WebApplicationProxy.Create(webFolder.FullName, true);

The rest of the callstack is 

```
xxx.yyy.Web.dll!CVS.Manage.Web.Global.Application_Start(object sender, System.EventArgs e) Line 117 C#
[External Code] 
Fritz.WebFormsTest.dll!Fritz.WebFormsTest.WebApplicationProxy.TriggerApplicationStart(System.Web.HttpApplication app) Line 341  C#
Fritz.WebFormsTest.dll!Fritz.WebFormsTest.WebApplicationProxy.InitializeInternal() Line 85  C#
Fritz.WebFormsTest.dll!Fritz.WebFormsTest.WebApplicationProxy.Create(string rootFolder, bool skipCrawl) Line 53 C#
```

// truncated a bit here

**Comment by csharpfritz** [comment]
Interesting...  It looks like an order of events thing.

I'll lift some of this code and drop it into a unit test.

Jeff

**Comment by KathleenDollard** [comment]
One more extreme weirdness. I have three tests, the other two give that error on either debug or run. That test gives a different error on run. ??

**Comment by KathleenDollard** [comment]
Well, since this is a mixed WebForms and MVC project, not too surprising that there are hiccups.

**Comment by csharpfritz** [comment]
This could get messy as the AreaRegistration reaches into the compiled file
cache to look up the list of types that inherit from AreaRegistration in
order to execute them.

The compiled file cache is written as an XML file into the precompiled
application folder.

Jeff

**Comment by csharpfritz** [comment]
This MVC issue is caused when the application attempts to dip back into the BuildManager and grab the types in the AppDomain that inherit from AreaRegistration.

Possible solutions:
-  Create a TestApplication that inherits from HttpApplication and provides an AreaRegistration property that contains a RegisterAllAreas method that performs the same tasks as the real method, but uses reflection instead
-  Write a MVC-AreaRegistrationTypeCache.xml file to the precompilation folder that contains at least one reference to an AreaRegistration object.  This will eliminate the call to the BuildManager as the AreaRegistration types will be returned directly.  We would need to pay particular attention to the deserialization of this file that takes place within [TypeCacheSerializer.DeserializeTypes](http://aspnetwebstack.codeplex.com/SourceControl/changeset/view/5fa60ca38b5837cc843b5d4552113f9a0235c3bf#src/System.Web.Mvc/TypeCacheSerializer.cs)
